import type { Metadata } from "next";
import "./globals.css";
import Modal from "@/components/modal";

export const metadata: Metadata = {
  title: "Trello Clone With AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#f5f6f8]">
        {children}
        <Modal />
      </body>
    </html>
  );
}
