import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/navbar";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Online Resume V2",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  education,
}: Readonly<{
  children: React.ReactNode;
  education: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider
          appearance={{
            variables: {
              colorText: "#fff",
              colorPrimary: "#0E78F9",
              colorBackground: "#1c1f2e",
              colorInputBackground: "#252a41",
              colorInputText: "white",
            },
            layout: {
              logoImageUrl: "/resume-icon.png",
              socialButtonsVariant: "iconButton",
            },
          }}
        >
          <NavBar />
          {children}
          {education}
        </ClerkProvider>
      </body>
    </html>
  );
}
