import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "",
    template: "",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          Root Layout Header
        </header>
        {children}
        <footer style={{ backgroundColor: "navajowhite" }}>
          Root Layout Footer
        </footer>
      </body>
    </html>
  );
}
